name: Publish Node.js package for release
on:
  release:
    types: [created]
jobs:
  # Performs quick checks before the expensive test runs
  check-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint source code
        run: npm run lint

  # Compile the typescript
  build_and_publish:
    needs: [check-and-lint]

    runs-on: ${{ matrix.os }}

    permissions: 
      contents: read
      packages: write 

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run build script
        run: npm run build

      # # Setup .npmrc file to publish to npm
      # - name: Setup .npmrc file to publish to npm
      #   uses: actions/setup-node@v2
      #   with:
      #     registry-url: 'https://registry.npmjs.org'
        
      # # Publish to npm
      # - name: Publish to npmjs registry
      #   run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Setup .npmrc file to publish to GitHub Packages
      - name: Setup .npmrc file to publish to GitHub Packages
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'

      # Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
